# Generated by Django 4.2.7 on 2025-08-10 19:41

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgi',
            name='supported_horizons',
        ),
        migrations.RemoveField(
            model_name='sgi',
            name='supported_objectives',
        ),
        migrations.RemoveField(
            model_name='sgi',
            name='supported_risk_levels',
        ),
        migrations.RemoveField(
            model_name='sgi',
            name='total_assets_under_management',
        ),
        migrations.RemoveField(
            model_name='sgi',
            name='total_clients',
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL, verbose_name='Vérifié par'),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Révisé par'),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sgi',
            name='historical_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('-100')), django.core.validators.MaxValueValidator(Decimal('1000'))], verbose_name='Performance historique (%)'),
        ),
    ]
