# Generated by Django 4.2.7 on 2025-08-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invested_amount', models.DecimalField(decimal_places=2, help_text='Montant investi en FCFA', max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, help_text='Valeur actuelle en FCFA', max_digits=15)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sgi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sgi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investissement Utilisateur',
                'verbose_name_plural': 'Investissements Utilisateurs',
                'db_table': 'user_investments',
            },
        ),
        migrations.CreateModel(
            name='UserDashboardStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_portfolio_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('global_performance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_month_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('savings_rank', models.IntegerField(default=0)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistiques Dashboard',
                'verbose_name_plural': 'Statistiques Dashboard',
                'db_table': 'user_dashboard_stats',
            },
        ),
        migrations.CreateModel(
            name='DashboardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('INVESTMENT', 'Investissement'), ('WITHDRAWAL', 'Retrait'), ('SAVINGS', 'Épargne'), ('DIVIDEND', 'Dividende'), ('FEE', 'Frais')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant en FCFA', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('PROCESSED', 'Traité'), ('CANCELLED', 'Annulé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('description', models.TextField(help_text='Description de la transaction')),
                ('reference_id', models.CharField(help_text='Référence unique', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.userinvestment')),
                ('savings_challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.savingschallenge')),
                ('sgi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sgi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Dashboard',
                'verbose_name_plural': 'Transactions Dashboard',
                'db_table': 'dashboard_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSavingsProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, help_text='Montant épargné en FCFA', max_digits=15)),
                ('streak_days', models.IntegerField(default=0, help_text="Jours consécutifs d'épargne")),
                ('last_saving_date', models.DateTimeField(blank=True, null=True)),
                ('badges_earned', models.JSONField(default=list, help_text='Liste des badges obtenus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.savingschallenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression Épargne',
                'verbose_name_plural': 'Progressions Épargne',
                'db_table': 'user_savings_progress',
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
