# Generated by Django 4.2.7 on 2025-08-26 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userinvestment_userdashboardstats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxFinancier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('revenus', 'Revenus'), ('depenses', 'Dépenses')], max_length=10)),
                ('categorie', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flux_financiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flux Financier',
                'verbose_name_plural': 'Flux Financiers',
                'db_table': 'flux_financiers',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='flux_financ_user_id_335d1b_idx'), models.Index(fields=['user', 'type'], name='flux_financ_user_id_7908ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='BilanFinancier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('total_revenus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_depenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('suggestions_generees', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilans_financiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bilan Financier',
                'verbose_name_plural': 'Bilans Financiers',
                'db_table': 'bilans_financiers',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'periode_debut', 'periode_fin')},
            },
        ),
    ]
