# Generated by Django 4.2.7 on 2025-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sgi_supported_horizons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="Adresse email unique pour l'authentification", max_length=254, unique=True, verbose_name='Email address'),
        ),
    ]
