# Generated by Django 4.2.7 on 2025-08-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fluxfinancier_bilanfinancier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='country_of_origin',
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Client'), ('BASIC', 'Utilisateur de base'), ('SGI_MANAGER', 'Manager SGI'), ('INSTRUCTOR', 'Formateur'), ('SUPPORT', 'Support'), ('ADMIN', 'Administrateur'), ('STUDENT', 'Étudiant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Client/Épargnant'), ('BASIC', 'Utilisateur de base'), ('STUDENT', 'Étudiant/Apprenant'), ('SGI_MANAGER', 'Manager SGI'), ('INSTRUCTOR', 'Instructeur/Formateur'), ('SUPPORT', 'Support Client'), ('ADMIN', 'Administrateur')], default='CUSTOMER', max_length=20),
        ),
    ]
