# Generated by Django 4.2.7 on 2025-08-30 16:12

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_country_of_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(default='Ressources Challenge Épargne', max_length=200, verbose_name='Titre de la bannière')),
                ('banner_description', models.TextField(default="Découvrez toutes les ressources nécessaires pour réussir votre challenge d'épargne", verbose_name='Description de la bannière')),
                ('youtube_video_id', models.CharField(default='dQw4w9WgXcQ', help_text="Entrez uniquement l'ID de la vidéo YouTube (ex: dQw4w9WgXcQ)", max_length=50, verbose_name='ID de la vidéo YouTube')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenu des Ressources',
                'verbose_name_plural': 'Contenus des Ressources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Cette adresse email est déjà utilisée.'}, help_text="Adresse email unique pour l'authentification", max_length=254, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': "Ce nom d'utilisateur est déjà utilisé."}, help_text='Requis. 150 caractères ou moins. Lettres, chiffres et @/./+/-/_ seulement.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
