# Generated by Django 4.2.7 on 2025-08-21 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fix_admin_log_user_id'),
        ('core', '0004_categorie_souscategorie_banniere_actualites_and_more'),
    ]

    operations = [
    ]
