# Generated by Django 4.2.7 on 2025-08-31 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resourcecontent_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Code unique d'accès à la cohorte", max_length=20, unique=True)),
                ('nom', models.CharField(help_text='Nom de la cohorte (ex: Cohorte Janvier 2024)', max_length=100)),
                ('mois', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], help_text='Mois de la cohorte (1-12)')),
                ('annee', models.IntegerField(default=2025, help_text='Année de la cohorte')),
                ('email_utilisateur', models.EmailField(help_text="Email de l'utilisateur pour vérification", max_length=254)),
                ('actif', models.BooleanField(default=True, help_text='Indique si la cohorte est active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Utilisateur associé à cette cohorte', on_delete=django.db.models.deletion.CASCADE, related_name='cohortes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cohorte',
                'verbose_name_plural': 'Cohortes',
                'db_table': 'cohortes',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('user', 'mois', 'annee')},
            },
        ),
    ]
