# Generated by Django 4.2.7 on 2025-08-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cohorte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohorte',
            name='code',
            field=models.CharField(blank=True, help_text="Code unique d'accès à la cohorte (généré automatiquement)", max_length=50, unique=True),
        ),
    ]
