# Generated by Django 4.2.7 on 2025-08-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_managers'),
    ]

    operations = [
    ]
