# Generated by Django 4.2.7 on 2025-08-23 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_challengeparticipation_savingsgoal_savingsdeposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsdeposit',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='savingsdeposit',
            name='user',
            field=models.ForeignKey(default='37c1c8f9-4cda-4fab-9cf9-9ad47a67e792', on_delete=django.db.models.deletion.CASCADE, related_name='savings_deposits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsdeposit',
            name='participation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.challengeparticipation'),
        ),
    ]
