# Generated by Django 4.2.7 on 2025-08-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_savingsdeposit_bank_name_savingsdeposit_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsdeposit',
            name='user',
        ),
    ]
