# Generated by Django 4.2.7 on 2025-08-25 00:04

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_savingsdeposit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_goal_set_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de définition de l'objectif mensuel"),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_savings_goal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name="Objectif d'épargne mensuel (FCFA)"),
        ),
    ]
