# Generated by Django 4.2.7 on 2025-08-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification_webhookendpoint_notificationtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_range',
            field=models.CharField(blank=True, choices=[('moins_de_18', 'Moins de 18 ans'), ('18_24', '18-24 ans'), ('25_35', '25-35 ans'), ('36_45', '36-45 ans'), ('46_55', '46-55 ans'), ('plus_de_55', 'Plus de 55 ans')], max_length=20, null=True, verbose_name="Tranche d'âge"),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays de résidence'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, null=True, verbose_name='Genre'),
        ),
    ]
